### PR TITLE
Tiramisu is no longer needed to mod vWii

### PR DESCRIPTION
**Pull request by tnvu**
vWii Compat Installer has a wuhb file now and can be executed directly from Aroma.

Downloading Tiramisu is unnecessary.

### CODE REVIEW

**Comment by VannyBuns** [comment]
The vWii guide is being moved to Wii.hacks, so it doesn't really matter anymore. And the guide was rewritten to use the version that works on both environments anyway (the .rpx).

**Comment by tnvu** [comment]
That's good to hear. It will be nice to have it all consolidated in a single place.

Do you have any idea when that will be done?

Since wiiu.hacks is still the primary source of information for vWii modding, it seems to make sense for it to be correct -- even if it's only until wii.hacks takes over.

**Comment by VannyBuns** [comment]
According to the Wii helpers, it is almost ready for review. No specific ETA, but won't it be too long.

For the time being, I'll convince the maintainers of the Wii U guide to make the vWii guide use aroma.

**Comment by Lazr1026** [comment]
Well, now that the vwii guide is using aroma now, i dont see a need to keep this open. was given no real ETA for vwii on the wii guide, so this is fine for now.

**Pull request closed without merging**
