### PR TITLE
add aroma to sidebar

### PR DESCRIPTION
**Pull request by SirGamers**
yes

### CODE REVIEW

**Comment by Lazr1026** [comment]
why dont we just make Aroma the primary environment, what is what #195 is doing.

**Comment by SirGamers** [comment]
> why dont we just make Aroma the primary environment, what is what #195 is doing.

Tiramisu is more stable than Aroma at this time

**Comment by SirGamers** [comment]
> i would say they are equal. whatever bugs that were in aroma when it was introduced are mostly fixed

well you should at least add it to the archive instead of straight up deleting it

**Comment by Lazr1026** [comment]
that...is probably a good idea.

**Comment by SirGamers** [comment]
i made a pr
gonna do it for ya

**Comment by SirGamers** [comment]
@Lazr1026 [pr is done](https://github.com/Lazr1026/Guide-WiiU/pull/1)

**Pull request closed without merging**
